spring.application.name=CustomerService
server.port=8081

# ===============================
# PostgreSQL - Neon Database
# ===============================
spring.datasource.url=jdbc:postgresql://ep-calm-dew-ay34eqph-pooler.c-5.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_h0lQue5dGAFN

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# Connection Pool
# ===============================
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=30000